/*
  build-dwca — field-record data ingest.
  --------------------------------------
  Reads scripts/ingest/places.config.json (the editorial skeleton),
  enriches each actor with authoritative GBIF taxonomy + a real occurrence
  coordinate, and each interaction with GloBI evidence + citation, then
  writes a Darwin Core Archive per place into public/dwca/<id>/ in the
  exact schema the field-record scrollytelling reads
  (occurrence.txt + resource-relationship.txt + meta.xml + eml.xml).

  Run: npm run ingest            (all places)
       npm run ingest sundarbans (one place)

  The committed Sundarbans archive doubles as the offline fallback, so the
  site never depends on a live network. Re-running upgrades a place to
  real, sourced data without any code change.
*/

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { gbifMatch, gbifOccurrenceInBbox, gbifSpeciesUrl } from './gbif.mjs';
import { globiEvidence, RO } from './globi.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const CONFIG = JSON.parse(readFileSync(resolve(__dirname, 'places.config.json'), 'utf8'));

const clean = (v) => String(v == null ? '' : v).replace(/[\t\n\r]+/g, ' ').trim();
const jitter = (base, i) => +(base + ((i * 37) % 17 - 8) * 0.004).toFixed(4); // tiny spread around center

function meta(place) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Darwin Core Archive descriptor. Core: Occurrence; Extension:
     ResourceRelationship (GloBI / OBO Relations Ontology interaction
     terms). Generated by scripts/ingest/build-dwca.mjs. -->
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="UTF-8" fieldsTerminatedBy="\\t" linesTerminatedBy="\\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files><location>occurrence.txt</location></files>
    <id index="0"/>
${[
  'occurrenceID', 'basisOfRecord', 'scientificName', 'vernacularName', 'taxonRank',
  'kingdom', 'phylum', 'class', 'order', 'family', 'decimalLatitude', 'decimalLongitude',
  'coordinateUncertaintyInMeters', 'locality', 'habitat', 'countryCode', 'eventDate',
  'month', 'associatedReferences', 'dynamicProperties',
].map((t, i) => `    <field index="${i}" term="http://rs.tdwg.org/dwc/terms/${t}"/>`).join('\n')}
  </core>
  <extension encoding="UTF-8" fieldsTerminatedBy="\\t" linesTerminatedBy="\\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/ResourceRelationship">
    <files><location>resource-relationship.txt</location></files>
    <coreid index="1"/>
${[
  'resourceRelationshipID', 'resourceID', 'relatedResourceID', 'relationshipOfResource',
  'relationshipOfResourceID', 'relationshipAccordingTo', 'relationshipEstablishedDate',
  'relationshipRemarks',
].map((t, i) => `    <field index="${i}" term="http://rs.tdwg.org/dwc/terms/${t}"/>`).join('\n')}
  </extension>
</archive>
`;
}

function eml(id, place) {
  const [w, s, e, n] = place.bbox;
  return `<?xml version="1.0" encoding="UTF-8"?>
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" packageId="species-on-screen/dwca/${id}/v1" system="species-on-screen" scope="system" xml:lang="en">
  <dataset>
    <title xml:lang="en">${place.name} Field Record: a ${place.type.toLowerCase()} interaction web</title>
    <creator><organizationName>Species on Screen — Eco-Cinema Observatory</organizationName></creator>
    <pubDate>${new Date().toISOString().slice(0, 10)}</pubDate>
    <language>en</language>
    <abstract><para>An attested, illustrative interaction dataset for ${place.name} (${place.locality}). Occurrences — species and the human community (Homo sapiens) — are placed in the landscape and linked by resource relationships typed with OBO Relations Ontology terms (as the Global Biotic Interactions network uses them). Taxonomy is the GBIF backbone; interactions are sourced from GloBI where present and from the cited literature otherwise. Coordinates are representative georeferenced occurrences within the reserve.</para></abstract>
    <intellectualRights>
      <para>This work is licensed under a <ulink url="https://creativecommons.org/licenses/by/4.0/legalcode"><citetitle>Creative Commons Attribution (CC BY) 4.0 License</citetitle></ulink>.</para>
    </intellectualRights>
    <coverage>
      <geographicCoverage>
        <geographicDescription>${place.locality}</geographicDescription>
        <boundingCoordinates>
          <westBoundingCoordinate>${w}</westBoundingCoordinate>
          <eastBoundingCoordinate>${e}</eastBoundingCoordinate>
          <northBoundingCoordinate>${n}</northBoundingCoordinate>
          <southBoundingCoordinate>${s}</southBoundingCoordinate>
        </boundingCoordinates>
      </geographicCoverage>
    </coverage>
  </dataset>
</eml:eml>
`;
}

async function buildPlace(id, place) {
  console.log(`\n[${id}] ${place.name} — ${place.actors.length} actors, ${place.interactions.length} interactions`);
  const idOf = new Map();
  const occRows = [];
  const country = place.countries[0] || '';

  for (let i = 0; i < place.actors.length; i++) {
    const a = place.actors[i];
    const occId = `${id.toUpperCase()}:OCC:${i + 1}`;
    idOf.set(a.sci, occId);

    const tax = await gbifMatch(a.sci);
    let lat = place.center.lat, lng = place.center.lng, uncertainty = 10000, occCount = 0, key = null;
    if (tax && tax.usageKey) {
      key = tax.usageKey;
      const occ = await gbifOccurrenceInBbox(tax.usageKey, place.bbox);
      if (occ) { occCount = occ.count || 0; if (occ.lat != null) { lat = occ.lat; lng = occ.lng; uncertainty = 5000; } }
    }
    if (uncertainty === 10000) { lat = jitter(place.center.lat, i); lng = jitter(place.center.lng, i); }

    const dyn = {
      sceneX: a.sceneX, sceneY: a.sceneY, trophicRole: a.role, iucnCategory: a.iucn,
      seasonalPresence: a.season, cascadeFailOrder: a.fail,
      gbifTaxonKey: key, gbifOccurrenceCount: occCount,
    };
    const refs = key ? `GBIF Backbone Taxonomy: ${gbifSpeciesUrl(key)}` : 'GBIF backbone (no match); see CREDITS.md';
    occRows.push([
      occId, a.basisOfRecord || 'HumanObservation', a.sci, a.vern, (tax && tax.taxonRank) || 'species',
      (tax && tax.kingdom) || '', (tax && tax.phylum) || '', (tax && tax.class) || '',
      (tax && tax.order) || '', (tax && tax.family) || '',
      lat, lng, uncertainty, place.locality, place.habitat, country, place.eventDate, a.month || 0,
      refs, JSON.stringify(dyn),
    ].map(clean).join('\t'));
    console.log(`   · ${a.sci.padEnd(26)} ${tax ? 'GBIF ✓ (' + (tax.family || '?') + ')' : 'GBIF —'}  occ:${occCount}`);
  }

  const relRows = [];
  let r = 0;
  for (const it of place.interactions) {
    r++;
    const from = idOf.get(it.from), to = idOf.get(it.to);
    if (!from || !to) { console.warn(`   ! interaction skipped (unknown actor): ${it.from} -> ${it.to}`); continue; }
    const ev = await globiEvidence(it.from, it.to, it.type);
    // Prefer the curated literature citation (specific); fall back to
    // GloBI's study citation; record GloBI corroboration in the remark.
    const according = it.litCitation || (ev.found ? ev.citation : 'Global Biotic Interactions (GloBI)');
    const remark = `${it.remark ? it.remark + ' ' : ''}seasonal:${it.season || 'all'} ${ev.found ? `Corroborated in GloBI (${ev.count}+ record(s)).` : '(literature record; not yet in GloBI).'}`;
    relRows.push([
      `${id.toUpperCase()}:REL:${r}`, from, to, it.type, RO[it.type] || '',
      according, '', remark,
    ].map(clean).join('\t'));
    console.log(`   · ${it.from} ${it.type} ${it.to.padEnd(22)} ${ev.found ? 'GloBI ✓' : 'lit'}`);
  }

  const dir = resolve(ROOT, 'public/dwca', id);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const occHead = 'occurrenceID\tbasisOfRecord\tscientificName\tvernacularName\ttaxonRank\tkingdom\tphylum\tclass\torder\tfamily\tdecimalLatitude\tdecimalLongitude\tcoordinateUncertaintyInMeters\tlocality\thabitat\tcountryCode\teventDate\tmonth\tassociatedReferences\tdynamicProperties';
  const relHead = 'resourceRelationshipID\tresourceID\trelatedResourceID\trelationshipOfResource\trelationshipOfResourceID\trelationshipAccordingTo\trelationshipEstablishedDate\trelationshipRemarks';
  writeFileSync(resolve(dir, 'occurrence.txt'), occHead + '\n' + occRows.join('\n') + '\n');
  writeFileSync(resolve(dir, 'resource-relationship.txt'), relHead + '\n' + relRows.join('\n') + '\n');
  writeFileSync(resolve(dir, 'meta.xml'), meta(place));
  writeFileSync(resolve(dir, 'eml.xml'), eml(id, place));
  // Per-place credits/provenance (so the field-record's link never 404s).
  const cites = [...new Set(place.interactions.map((it) => it.litCitation).filter(Boolean))];
  writeFileSync(resolve(dir, 'CREDITS.md'), `# ${place.name} field record — credits & provenance\n\n`
    + `Generated by \`scripts/ingest/build-dwca.mjs\` on ${new Date().toISOString().slice(0, 10)}.\n\n`
    + `## Data\n\n- **Taxonomy:** GBIF Backbone Taxonomy (per-occurrence \`associatedReferences\`).\n`
    + `- **Coordinates:** representative georeferenced GBIF occurrences within the reserve bounding box (see \`coordinateUncertaintyInMeters\`).\n`
    + `- **Interactions:** typed with OBO Relations Ontology terms; corroborated in the Global Biotic Interactions network (GloBI) where present, otherwise from the literature below.\n\n`
    + `## Interaction literature\n\n${cites.map((c) => `- ${c}`).join('\n')}\n\n`
    + `## Sound\n\nProcedural biome bed generated in the browser; openly-licensed field recordings credited here as added.\n`);
  console.log(`   → public/dwca/${id}/  (occurrence.txt, resource-relationship.txt, meta.xml, eml.xml)`);
  return { id, name: place.name, type: place.type, actors: place.actors.length, interactions: relRows.length };
}

async function main() {
  const only = process.argv[2];
  const ids = Object.keys(CONFIG).filter((k) => k !== '_comment' && (!only || k === only));
  if (!ids.length) { console.error('No matching place in places.config.json:', only); process.exit(1); }
  const index = [];
  for (const id of ids) index.push(await buildPlace(id, CONFIG[id]));
  // No dwca/index.json is written (retired in M27): the canonical registry of
  // places is cinematic-language/place-manifest.json (ADR-001 single source of
  // truth), which `check-manifest` validates against each archive's actual row
  // counts. Regenerating an archive that changes its actor/interaction counts
  // requires updating the manifest's dwca counts, which the validator enforces.
  console.log(`\n✓ ingest complete: ${index.map((p) => p.id).join(', ')}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
